resources:
- ../../../../base/prometheus
- prometheus-pv.yaml

patches:
  - target:
      kind: HelmRelease
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/externalLabels/cluster
        value: kim7s