resources:
  - sealed-secrets
  - apigateway
  - cert-manager
  - base-certificate/kustomization.flux.yaml
  - metrics-server
  - observability
  - storage-class.yaml
  - gatewayapi/kustomization.flux.yaml
  - http-echo