resources:
  - ../../../../base/grafana/grafana-alloy
  - access-policy.sealed.yaml

patches:
  - target:
      kind: HelmRelease
      name: grafana-alloy
    patch: |-
      - op: replace
        path: /spec/values/cluster/name
        value: kim7s
      - op: replace
        path: /spec/values/alloy-logs/alloy/extraEnv/0/value
        value: kim7s
      - op: replace
        path: /spec/values/alloy-singleton/alloy/extraEnv/0/value
        value: kim7s