namespace: dns-server
resources:
  - namespace.yaml
  - ../../../base/bind9/

configMapGenerator:
  - name: bind9-config
    files:
      - "internal-kim-tec-br.zone=config/internal-kim-tec-br.zone"
      - "named.conf=config/named.conf"

patches:
  - path: service.patch.yaml
