apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitor-resources
spec:
  interval: 10m
  path: "./overlays/kimawesome/infrastructure/observability/monitors-infrastructure"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infrastructure
      namespace: flux-system