apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: http-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: http-echo
    spec:
      securityContext:
        fsGroup: 41808
        supplementalGroups: [41808]
      containers:
        - name: http-echo
          image: mendhak/http-https-echo:33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 41808
            runAsNonRoot: true
            runAsUser: 41808
            capabilities:
              drop:
                - ALL
